### ISSUE TITLE
GIS.lab Web: Upgrade Django codebase to Python 3

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab-web#18]
Upgrade Django codebase to Python 3

**Comment by marcel-dancak** [comment]
I have already upgraded server's codebase in 'python3' branch.

One more thing will be needed to configure, folder with 'custom_settings.py' must be in PYTHON_PATH, because relative imports seems to be not supported in Python 3.

Should I also update vagrant scripts?

**Comment by marcel-dancak** [comment]
Merged with master
