### ISSUE TITLE
empty overlay tiles

### ISSUE THREAD

**Issue by jachym** [gislab-npo/gislab-web#23]
I can not see any overlay map. Using fresh master and vagrant destroy && vagrant up. Result is always the same - transparent empty tile image

**Comment by imincik** [comment]
Try to update 'natural-earth.sqlite' file, which was updated with Pseudo Mercator geometry field 
```
$ rm dev/publish/user/natural-earth/natural-earth.sqlite
$ wget https://raw.githubusercontent.com/gislab-npo/gislab/master/gislab-project/natural-earth/natural-earth.sqlite
$ rm -r dev/publish
```

**Comment by landam** [comment]
btw, why

```
rm -r dev/publish
```

it will delete all projects

**Comment by imincik** [comment]
Sorry, it should be
```
$ rm -r dev/django/media/cache
```

**Comment by imincik** [comment]
It is working in current master. I am closing this issue.

**Comment by jachym** [comment]
well, I've tried and it did not help: I see only "other country" slovenia

**Comment by jachym** [comment]
so .. vagrant provision seemed to work. closing for all
