### ISSUE TITLE
ansible_ssh_user is undefined 

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab-web#25]
At the end of vagrant up I have this error.

TASK [Create shared development directory] *************************************
fatal: [gislab-web]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible_ssh_user' is undefined"}

**Comment by imincik** [comment]
@abusquets,
I guess you are running Ansible 2.0 which is currently not supported yet. We are using Ansible 1.9 for  which is not compatible with version 2.0. Unfortunately, 'ansible_ssh_user' was renamed to 'ansible_user' in 2.0.

Please use Ansible 1.9 and try again.

**Comment by abusquets** [comment]
Yes, I use Ansible 2.0, I'll try with Ansible 1.9.
Thanks

**Comment by landam** [comment]
Probably `vagrant up` could end up with error when Ansible >=2 is used.

**Comment by imincik** [comment]
Hi @landam ,
I am working on vagrant environment refactoring in 'vagrant-refactoring' branch. Ansible version was just pushed there (https://github.com/gislab-npo/gislab-web/commit/30d15c15a7932103abeb70427f6c53e14533286f)
