### ISSUE TITLE
GIS.lab Web: Vector layer is not displayed

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gislab-web#33]
I have QGIS project:

![qgis_project](https://cloud.githubusercontent.com/assets/13394357/13393207/30399942-dee0-11e5-825d-d9bcb703e05d.png)

using GIS.lab plugin settings

![qgis_plugin](https://cloud.githubusercontent.com/assets/13394357/13393308/dc6ae7d4-dee0-11e5-9d0f-996583b3eb5a.png)

result in web

![qgis_web](https://cloud.githubusercontent.com/assets/13394357/13393215/3f27c906-dee0-11e5-9e74-a907963296a6.png)

**Comment by imincik** [comment]
Support for vector layer is not implemented and will be removed in 1.0 - see #6

**Comment by marcel-dancak** [comment]
I think there is a misunderstanding here, from these screenshots it seems that she doesn't published 'contour' vector layers as a real vector layer. That's the functionality which was in previous version and will be removed from plugin. She has a project with one vector and two raster layers, but all layers are published the same way, so there is a problem somewhere.

**Comment by marcel-dancak** [comment]
Ľudka, can you send me this project (with .meta file)?

**Comment by imincik** [comment]
Sorry @lfurtkevicova . @marcel-dancak you are right.

**Comment by lfurtkevicova** [comment]
there is my project (data + project + meta)

[gismentors.tar.gz](https://github.com/gislab-npo/gislab-web/files/150928/gismentors.tar.gz)

btw I don't undertand .. yesterday it worked, see [my WEB project with vectors] (https://github.com/lfurtkevicova/kn-stuff/wiki/Priklady-v-praxi#web) .. I did not notice [#6] (https://github.com/gislab-npo/gislab-web/issues/6)

**Comment by lfurtkevicova** [comment]
ok, it is working .. there were two kinds of contours .. (before and after clipping) ..

**Comment by lfurtkevicova** [comment]
but this time GIS.lab print does not work

![print](https://cloud.githubusercontent.com/assets/13394357/13396311/2cbbea2c-def4-11e5-851c-9c8e946d3e60.png)

**Comment by landam** [comment]
@lfurtkevicova how the broken print is related to this issue?

**Comment by lfurtkevicova** [comment]
in no way

**Comment by landam** [comment]
So please report it as an new issue. Thanks.

**Comment by marcel-dancak** [comment]
I still don't understand why is 'contour' layer visible in QGIS and not visible in Web, but if you know the reason, I let this issue closed.

And Print should be disabled for projects without defined print templates, we know about it and it will be done soon.

**Comment by lfurtkevicova** [comment]
This was partly related to internal QGIS stuff I mean (clipping contours) .. Firstly it was project with larger area .. the respond was too slow, so I clipped all layers. After recreating project it is ok. I don't understand, too. We can close this issue!
