### ISSUE TITLE
QGIS Plugin: Not possible to continue when title is set after warning message

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gislab-web#35]
The title should be set in the third dialog box. When I forget to set it there is warning message (that is OK). But when I set it and I want to continue, it is impossible. For me this is very user unfriendly ..
IMHO title should be set in the first widget.

**Comment by landam** [comment]
I are probably speaking about QGIS plugin, right? Please add some screenshot to be sure what you mean by "third dialog box".

**Comment by lfurtkevicova** [comment]
I mean *Project* part ..

![project_title](https://cloud.githubusercontent.com/assets/13394357/14209599/37de04f4-f825-11e5-86fe-9765c61e6736.png)

**Comment by landam** [comment]
OK, I would suggest to move 'Project' tab to the first position.

```
Project | Base layer | Layers
```

Whtat do you think?

**Comment by lfurtkevicova** [comment]
Maybe it is only my fault, but from my point of view it will be better .. Or just set some default title .. not to block user to continue without title ..

**Comment by marcel-dancak** [comment]
There is one important reason for original order of the tabs - configuration in Base Layer tab influence settings in Project tab - list of available scales. Project title is important field, and in normal case it should be already set in QGIS project before you try to publish it, so I wouldn't change tabs order because of this issue.

From my point of view it is bug in wizard implementation. User should be able to set title field after this error and continue on second page after successful page validation.

**Comment by landam** [comment]
@marcel-dancak: You are right, the order of tabs should remain. The project title is set from QGIS project in normal case.
@lfurtkevicova: The project title is newly checked after setting up the page from existing metadata, so the user should get this information without need to click on Next button. Make sense to you?

**Comment by lfurtkevicova** [comment]
better, thanks!

**Comment by lfurtkevicova** [comment]
@landam Something is wrongn in current *origin/master*. "Project title is missing ... "  immediately after GIS.lab plugin startup and it does not disappear after filling in.

**Comment by marcel-dancak** [comment]
I can only confirm this bug, and it's not related only to 'Title' field. If you configure first page in wizard wrong and some error is detected, it will disable Next button permanently so you are forced to close dialog and start again.

I think that in older version, validation on first wizard page was split into 2 functions:
* First one checked all constraints from project, which you can't in any way configure in plugin. This was checked only once right after dialog startup, and if any error was detected, Next button was disabled.
* Second validation was triggered every time Next button was pressed. If any errors was detected, they was logged and wizard stayed on this page. But Next button was left enabled, so you could fix issues and try again.

**Comment by landam** [comment]
@lfurtkevicova you are right, I have introduced the bug, should be fixed in 2e36d99

**Comment by landam** [comment]
@marcel-dancak you are right, by introducing `isComplete` mechanism I disabled second validation. From user POV it's a little bit strange that he/she can click on Next even there are errors reported and nothing happens. On the other hand we would need to process every widget to add or remove error messages (than isComplete is triggered automatically). The concept of second validation is a KISS solution. Let's keep it.

**Comment by lfurtkevicova** [comment]
I think we can close this issue!
