### ISSUE TITLE
GIS.lab Web NG - QGIS plugin

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab-web#6]
### TODO
* ~~add support for all supported base layers (see #3, #20 )~~
* ~~enable HTML content in Messages 'text' field~~
* ~~add possibility to publish all required files to 'Publish/USER' directory~~
* ~~Windows OS support~~
* ~~redesign of last two pages~~
* ~~remove publishing of QGIS layers as vector drawings in GeoJSON~~

### Coding style
* ~~convert tabs to spaces~~
* ~~80 characters on line~~

**Comment by landam** [comment]
Experimental support for MapBox and BingMaps implemented in d80d3a9

**Comment by landam** [comment]
I would like to propose new layout for base layer page, current layout:

![Image of current base layer layout](http://geo102.fsv.cvut.cz/~landa/github_issues/publish_dialog_base0.png)

Proposed layout based on groupboxes:

![Image of proposed base layer layout](http://geo102.fsv.cvut.cz/~landa/github_issues/publish_dialog_base1.png)

**Comment by imincik** [comment]
@landam, much better. Go on !

**Comment by landam** [comment]
@imincik New UI layout for base layers implemented in ba89916

**Comment by landam** [comment]
@imincik Proposal of new configuration summary page based on QTreeWidget:

![config_summary_new](https://cloud.githubusercontent.com/assets/5683186/12728573/bda5d1d4-c922-11e5-910d-027b8705c4a6.png)

Current layout:

![config_summary_old](https://cloud.githubusercontent.com/assets/5683186/12728582/c8b95316-c922-11e5-852b-16c41f5a8d1a.png)

**Comment by imincik** [comment]
@landam, looks very good.

**Comment by landam** [comment]
Proposal for new confirmation page layout:

![qgis-gislab-confirmation](https://cloud.githubusercontent.com/assets/5683186/13070735/005e255e-d48f-11e5-9d6e-d1845dd98dec.png)

**Comment by landam** [comment]
Slightly changed design for confirmation page:

(1) destination directory not set

![qgis-confirm-00](https://cloud.githubusercontent.com/assets/5683186/13244989/2eab9754-da0a-11e5-9292-4193cb1ef8a3.png)

(2) destination directory set by user

![qgis-confirm-01](https://cloud.githubusercontent.com/assets/5683186/13245004/4db906d6-da0a-11e5-8e3b-3024fd278e48.png)

**Comment by landam** [comment]
Confirmation page layout slightly changed, committed as e3e87b5
![gislab-confirmation1](https://cloud.githubusercontent.com/assets/5683186/13393791/f339afb0-dee3-11e5-87f0-2b813170c2e0.png)

**Comment by landam** [comment]
All tasks related to this issue should be done including Windows support.

![qgis-gislab-windows](https://cloud.githubusercontent.com/assets/5683186/14327567/2f9d42a2-fc33-11e5-8fd8-9a13dae3aa26.png)

Closing. Feel free to reopen if needed.
